app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    

]

if settings.DEBUG:
    urlpatterns += [
         path("__debug__/", include("debug_toolbar.urls")),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('deli/', views.deli, name='deli'),
    path('cont/', views.cont, name='cont'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

templates/base.html
 {% load static %} 
{% load goods_tags %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css  %}
    {% endblock css  %}
    <!-- Favicons for different platforms -->
    <link rel="" sizes="180x180" href="{% static "deps/favicon/" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/priv.png" %}">
    <link rel="" type="image/png" sizes="16x16" href="{% static "deps/favicon/" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<header class="d-flex justify-content-center bg-dark">
    <nav class="navbar navbar-expand-lg" data-bs-theme="dark">
        <a class="navbar-brand text-center"></a>
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0"></ul>
                <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                    <input class="form-control me-2" style="width: 350px;" type="search" name="q" placeholder="Поиск товаров" aria-label="Search">
                    <button class="btn btn-outline-success text-white border border-white" type="submit">Найти</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<header>
    <nav>
        <div class="d-flex justify-content-center bg-dark"
            style="position: fixed; bottom: 0; left: 0; height: 100vh; width: 240px;" data-bs-theme="dark">

            <img src="{% static "deps/favicon/logoaz.png" %}" alt="" style="width: 100%; height: 27vh; object-fit: cover;">
            <div class="vr"></div>
            <!-- Пустой блок на Ваше усмотрение -->
            <ul class="nav flex-column" style="position: absolute; top: 30vh;">
                <li class="nav-item"><a class="nav-link text-white" href="{% url "main:index" %}">Главный экран</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Каталог
                    </a>
                    <ul class="dropdown-menu">
                        {% tag_Categories as categories %}
                        {% for category in categories  %}
                            <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Информация
                    </a>
                    <ul class="dropdown-menu bg-dark">
                        <li><a class="dropdown-item text-white" href="{% url "main:deli" %}">Доставка и оплата</a></li>
                        <li><a class="dropdown-item text-white" href="{% url "main:cont" %}">Контактная информация</a></li>
                        <li><a class="dropdown-item text-white" href="{% url "main:about" %}">Про нас</a></li>
                    </ul>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link text-white" href="{% url "user:login" %}">Войти</a></li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Мой профиль
                        </a>
                        <ul class="dropdown-menu bg-dark"><li><a class="dropdown-item text-white" href="{% url "user:profile" %}">Личный кабинет</a></li>
                            <li><a class="dropdown-item text-white" href="{% url "user:users_cart" %}">Корзина</a></li>
                            {% if user.is_admin or user.is_staff %}
                                <li><a class="dropdown-item text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item text-white" href="{% url "user:logout" %}">Выйти</a></li>
                        </ul>
                    </li>
                {% endif %}
                {% block model_cart %}{% endblock %}
            </ul>
        </div>
    </nav>
</header>
        <!-- Контент -->
<div class="container">
    <div class="row mt-1">
        <div class="col-lg-2">
            <!-- Пустой блок на Ваше усмотрение -->
        </div>
        <div class="col-lg-10">
            <!-- Контент на странице -->
            {% include "includes/notifications.html" %}
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>
    {% block footer %}
    {% endblock footer %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script>
        $(document).ready(function() {
            $('.carousel-control-next').click(function() {
                $('#myCarousel').carousel('next');
            });
        
            $('.carousel-control-prev').click(function() {
                $('#myCarousel').carousel('prev');
            });
        });
        </script>

    </body>
    </html>